### ISSUE TITLE
Improvement - Update Bootstrap 4 components with Scania styling for 4.0.0-Beta.x

### ISSUE THREAD

**Issue by helloimela** [scania/scania-theme#11]
We need to have Scania look and styles implemented on these UI elements:
**In Intial part done for Corporate-ui 4.0.0-beta**
- [x] Scania colors #9 - Merged
- [x] Typography #36 - Merged
- [x] Buttons #14 - Merged
- [x] Button group #18  - Merged
- [x] Forms #15  - Merged
- [x] Dropdowns #17 - Merged
- [x] Tables  #16 - Merged
- [x] Modal #19 - Merged
- [x] Alert #20 - Merged
---
**In Intial part done for Corporate-ui 4.0.0-beta.1**
- [x] Badge - #27  Merged
- [x] Input group - #33 Merged
- [x] List group - #32 Merged
- [x] Breadcrumb - #26 Merged
- [x] Navs - #34 Merged
- [x] Pagination - #31 Merged
- [x] Progressbar - #29 Merged
- [x] Card - #52 Merged
---
**Future development**
- [ ] Tooltips (Needs JQuery in storybook)
- [ ] Popovers (Needs JQuery in storybook)
- [ ] Media object
- [ ] Images
- [ ] Spinners
- [ ] Jumbotron
- [ ] Figures
- [ ] Carousel
- [ ] Toasts
- [ ] Code

**Comment by mmexvr** [comment]
Everything done here is available in corporate-ui beta.1
